### PR TITLE
api: update youtube.js, switch between ios & web_embedded clients depending on request

### LINKED ISSUE #1173: Errors when downloading from YouTube
approx a week ago youtube pushed an update that enforced the po token for ±all googlevideo links from the android client, so we switched to the ios client to go around it on the main instance. today, it seems like youtube increased the ratio of an a/b test that makes the current ios client fail the precondition check when requesting the player (due to an old client version, now confirmed).

in cobalt it's displayed as this error (`error.api.fetch.fail`):

Image

if you log the actual error from youtube.js, you see this:

```
InnertubeError: Request to https://www.youtube.com/youtubei/v1/player?prettyPrint=false&alt=json failed with status 400
{
  "error": {
    "code": 400,
    "message": "Precondition check failed.",
    "errors": [
      {
        "message": "Precondition check failed.",
        "domain": "global",
        "reason": "failedPrecondition"
      }
    ],
    "status": "FAILED_PRECONDITION"
  }
}
```

any help is very welcome!

### PR DESCRIPTION
**Pull request by wukko**
this PR also changes the default client to IOS, so CUSTOM_INNERTUBE_CLIENT is no longer needed to get youtube functionality to work

closes #1173

### CODE REVIEW

File: api/src/processing/services/youtube.js [hunk 1]
```diff
@@ -86,13 +86,45 @@ const cloneInnertube = async (customFetch) => {
...
+    const useSession =
+        env.ytSessionServer && (
+            (
+                !useHLS
+                && innertubeClient === "IOS"
+                && (
+                    (quality > 1080 && o.format !== "h264")
+                    || o.format === "vp9")
+                )
+        );
```
Comment (dumbmoron) [inline api/src/processing/services/youtube.js:114]:
```suggestion
    const useSession =
        env.ytSessionServer && (
            (
                !useHLS
                && innertubeClient === "IOS"
                && (
                    (quality > 1080 && o.format !== "h264")
                    || o.format === "vp9")
            )
        );
```

Comment (wukko) [reply api/src/processing/services/youtube.js:114]: my bad

Comment (dumbmoron) [reply api/src/processing/services/youtube.js:114]: it's ok

Comment (dumbmoron) [reply api/src/processing/services/youtube.js]: cat

**Review by dumbmoron — APPROVED** [review]
image
