### PR TITLE
api: automatically pull youtube session tokens from a session server

### LINKED ISSUE #1173: Errors when downloading from YouTube
approx a week ago youtube pushed an update that enforced the po token for ±all googlevideo links from the android client, so we switched to the ios client to go around it on the main instance. today, it seems like youtube increased the ratio of an a/b test that makes the current ios client fail the precondition check when requesting the player (due to an old client version, now confirmed).

in cobalt it's displayed as this error (`error.api.fetch.fail`):

Image

if you log the actual error from youtube.js, you see this:

```
InnertubeError: Request to https://www.youtube.com/youtubei/v1/player?prettyPrint=false&alt=json failed with status 400
{
  "error": {
    "code": 400,
    "message": "Precondition check failed.",
    "errors": [
      {
        "message": "Precondition check failed.",
        "domain": "global",
        "reason": "failedPrecondition"
      }
    ],
    "status": "FAILED_PRECONDITION"
  }
}
```

any help is very welcome!

### PR DESCRIPTION
**Pull request by wukko**
if provided, cobalt will pull poToken & visitor_data from an instance of [invidious' youtube-trusted-session-generator](https://github.com/iv-org/youtube-trusted-session-generator) or its fork/counterpart (such as [yt-session-generator](https://github.com/imputnet/yt-session-generator), which we will use)

potentially closes #1173

### CODE REVIEW

File: api/src/processing/helpers/youtube-session.js [hunk 1]
```diff
@@ -0,0 +1,72 @@
...
+const validateSession = (session) => {
+    let parsed;
+    try {
+        parsed = JSON.parse(session);
+    } catch {
+        throw "invalid session response";
+    }
+
+    // https://github.com/iv-org/youtube-trusted-session-generator/blob/c2dfe3f/potoken_generator/main.py#L25
+    if (session.potoken < 160) {
```
Comment (dumbmoron) [inline api/src/processing/helpers/youtube-session.js:17]: length

Comment (wukko) [reply api/src/processing/helpers/youtube-session.js:17]: there's no github link shortener what can i even do

Comment (wukko) [reply api/src/processing/helpers/youtube-session.js:17]: oh shit

File: api/src/processing/helpers/youtube-session.js [hunk 2]
```diff
@@ -0,0 +1,76 @@
+import * as cluster from "../../misc/cluster.js";
+
+import { env } from "../../config.js";
+import { Green, Yellow } from "../../misc/console-text.js";
+
+let session = {};
```
Comment (dumbmoron) [inline api/src/processing/helpers/youtube-session.js:6]:
```suggestion
let session;
```

File: api/src/processing/helpers/youtube-session.js [hunk 3]
```diff
@@ -0,0 +1,76 @@
...
+}
+
+export const getYouTubeSession = () => {
+    // if session wasn't loaded on start, try to get it one more time
+    // instead of waiting for reload interval
+    if (!session.potoken) {
+        wrapLoad(true);
+    }
+    return session;
+}
```
Comment (dumbmoron) [inline api/src/processing/helpers/youtube-session.js:61]:
```suggestion
export const getYouTubeSession = () => {
    return session;
}
```

**Review by dumbmoron — CHANGES_REQUESTED** [review]

File: api/src/processing/helpers/youtube-session.js [hunk 4]
```diff
@@ -0,0 +1,62 @@
...
+
+export const getYouTubeSession = () => {
+    return session;
+}
+
+export const setup = () => {
+    if (cluster.isPrimary) {
+        wrapLoad(true);
+        if (env.ytSessionReloadInterval > 0) {
+            setInterval(() => wrapLoad(), env.ytSessionReloadInterval * 1000);
```
Comment (dumbmoron) [inline api/src/processing/helpers/youtube-session.js:53]:
```suggestion
            setInterval(wrapLoad, env.ytSessionReloadInterval * 1000);
```

File: api/src/processing/helpers/youtube-session.js [hunk 5]
```diff
@@ -0,0 +1,62 @@
...
+    loadSession()
+        .then(() => {
+            if (initial) {
+                console.log(`${Green('[✓]')} poToken & visitor_data loaded successfully!`);
+            }
+        })
+        .catch((e) => {
+            console.error(`${Yellow('[!]')} Failed loading poToken & visitor_data at ${new Date().toISOString()}.`);
+            console.error('Error:', e);
+        })
```
Comment (dumbmoron) [inline api/src/processing/helpers/youtube-session.js:42]:
```suggestion
    loadSession()
    .then(() => {
        if (initial) {
            console.log(`${Green('[✓]')} poToken & visitor_data loaded successfully!`);
        }
    })
    .catch((e) => {
        console.error(`${Yellow('[!]')} Failed loading poToken & visitor_data at ${new Date().toISOString()}.`);
        console.error('Error:', e);
    })
```

**Review by dumbmoron — CHANGES_REQUESTED** [review]

**Review by dumbmoron — DISMISSED** [review]
Screenshot 2025-03-19 at 14 56 53

**Review by dumbmoron — APPROVED** [review]
lgtm :3

**Review by dumbmoron — APPROVED** [review]
still lgtm
